# Generated by Django 5.1.4 on 2025-01-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('organization_id', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=250)),
                ('organization_type', models.CharField(max_length=100)),
                ('organization_logo', models.FileField(upload_to='media/')),
                ('ceo_name', models.CharField(max_length=100, null=True)),
                ('registered_year', models.CharField(max_length=50)),
                ('tax_number', models.CharField(max_length=100, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('website_url', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('alt_contact_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
    ]
