# Generated by Django 5.1.4 on 2025-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alt_contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
