# Generated by Django 5.1.4 on 2025-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_organization_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
