# Generated by Django 5.1.4 on 2025-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organizationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='media/profileImage/default.png', upload_to='uploads/'),
        ),
    ]
