# Generated by Django 5.1.4 on 2025-02-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_menu_role_rolepermission_role_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='media/profileImage/default.png', upload_to='media/'),
        ),
    ]
