# Generated by Django 5.1.4 on 2025-02-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_organization_organization_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organization'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
