# Generated by Django 5.1.4 on 2025-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_role_menus_remove_role_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(through='account.RolePermission', to='account.menu'),
        ),
    ]
