# Generated by Django 5.1.4 on 2025-02-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userdetails_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=100)),
                ('client_ratio', models.IntegerField()),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organization')),
            ],
        ),
    ]
